# Generated by Django 5.1.9 on 2025-05-31 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_cpf_gestor_alter_tenant_cpf_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('name', models.CharField(max_length=48, verbose_name='Nome')),
                ('social_name', models.CharField(blank=True, max_length=48, null=True, verbose_name='Nome Social')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(max_length=60, verbose_name='Data de Nascimento (DD/MM/AAAA)')),
                ('postcode', models.CharField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=60, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=30, verbose_name='Bairro')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('federated_unit', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('complement', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('phone_number', models.CharField(max_length=60, verbose_name='Telefone')),
                ('civil_status', models.CharField(choices=[('S', 'Solteira'), ('M', 'Casada'), ('W', 'Viúva'), ('J', 'Separada Judicialmente'), ('D', 'Divorciada'), ('C', 'União Estável')], max_length=1, verbose_name='Estado Civil')),
                ('spouse', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Cônjuge')),
                ('social_benefit', models.BooleanField(verbose_name='Benefício Social')),
                ('gender', models.CharField(choices=[('M', 'Homem'), ('F', 'Mulher'), ('T', 'Travesti'), ('W', 'Mulher Transexual')], max_length=1, verbose_name='Identidade de Gênero')),
                ('race', models.CharField(choices=[('W', 'Branco(a)'), ('M', 'Pardo(a)'), ('B', 'Negro(a)'), ('A', 'Amarelo(a)'), ('I', 'Indígena')], max_length=1, verbose_name='Raça')),
                ('sexual_orientation', models.CharField(choices=[('M', 'Héterossexual'), ('F', 'Bissexual'), ('H', 'Homossexual'), ('O', 'Outro')], max_length=1, verbose_name='Orientação Sexual')),
                ('education', models.CharField(choices=[('NA', 'Não Alfabetizada'), ('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('CT', 'Curso Tecnólogo'), ('ES', 'Ensino Superior'), ('PG', 'Pós Graduação'), ('CTP', 'Curso Técnico Profissionalizante'), ('EJA', 'EJA / Projovem e Afins')], max_length=4, verbose_name='Escolaridade')),
                ('occupation', models.CharField(choices=[('AUT', 'Autônoma'), ('EMP', 'Empregada'), ('DES', 'Desempregada'), ('DL', 'Do Lar'), ('AP', 'Aposentada/Pensionista')], max_length=4, verbose_name='Situação Ocupacional')),
                ('profession', models.CharField(max_length=60, verbose_name='Ocupação/Profissão')),
                ('work_status', models.CharField(choices=[('CTPS', 'Trabalhadora com CTPS'), ('SCTPS', 'Trabalhadora sem CTPS'), ('SP', 'Servidora Pública'), ('MIL', 'Militar'), ('CPS', 'Com Previdência Social'), ('SPS', 'Sem Previdência Social'), ('BPC', 'Benefício de Prestação Continuada')], max_length=5, verbose_name='Situação Trabalhista')),
                ('income', models.CharField(choices=[('M1SM', 'Menor de 1 SM'), ('1A3SM', 'de 1 a 3 SM'), ('3A6SM', 'Mais de 3 a 6 SM'), ('6A9SM', 'Mais de 6 a 9 SM'), ('9SM', 'Mais de 9 SM'), ('SR', 'Sem Renda')], max_length=5, verbose_name='Renda')),
                ('children', models.CharField(choices=[('C1', '1'), ('C2', '2'), ('C3', '3'), ('C4', '4'), ('C5', '5'), ('C6', '6'), ('C7+', '7 ou mais')], max_length=4, verbose_name='Total de Filhos')),
                ('deficiency', models.CharField(choices=[('PH', 'Física'), ('AU', 'Auditiva'), ('VI', 'Visual'), ('ME', 'Mental'), ('OT', 'Outras'), ('NO', 'Nenhuma')], max_length=2, verbose_name='Apresenta alguma deficiência/síndrome?')),
                ('deficiency_reason', models.BooleanField(verbose_name='Deficiência em decorrência da violência sofrida?')),
                ('has_consulted_psychiatrist', models.BooleanField(verbose_name='Já foi atendido por psiquiatra e/ou psicólogo?')),
                ('drug_usage', models.CharField(choices=[('MA', 'Maconha'), ('CO', 'Cocaína'), ('CR', 'Crack'), ('OT', 'Outras'), ('NO', 'Nenhuma')], max_length=2, verbose_name='Faz uso de drogas ilícitas?')),
                ('license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.license', verbose_name='Licença')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('qr_code', models.CharField(max_length=40, verbose_name='QR Code')),
                ('victim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='victims.victim', verbose_name='Vítima')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Token')),
                ('victim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='victims.victim', verbose_name='Vítima')),
            ],
        ),
        migrations.CreateModel(
            name='Aggression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledge', models.BooleanField(default=False, verbose_name='Confirmar')),
                ('type', models.CharField(choices=[('PB', 'Botão de pânico'), ('AD', 'Detecção por audio')], max_length=2)),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victims.victim')),
            ],
        ),
    ]
