# Generated by Django 5.1.9 on 2025-05-29 03:51

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('razao_social', models.CharField(default='', max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco_comercial', models.CharField(default='', max_length=255, verbose_name='Endereço Comercial')),
                ('inscricao_estadual', models.CharField(default='', max_length=255, verbose_name='Inscrição Estadual')),
                ('nome_do_gestor', models.CharField(default='', max_length=255, verbose_name='Nome do Gestor')),
                ('rg_gestor', models.CharField(default='', max_length=20, verbose_name='RG do Gestor')),
                ('cpf_gestor', models.CharField(default='', max_length=14, verbose_name='CPF do Gestor')),
                ('endereco_residencial', models.CharField(default='', max_length=255, verbose_name='Endereço Residencial')),
                ('data_nascimento_gestor', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Gestor')),
                ('cargo_gestor', models.CharField(default='', max_length=255, verbose_name='Cargo do Gestor')),
                ('unidade_executora', models.CharField(default='', max_length=255, verbose_name='Unidade Executora')),
                ('nome_responsavel', models.CharField(default='', max_length=255, verbose_name='Nome do Responsável')),
                ('funcao_responsavel', models.CharField(default='', max_length=255, verbose_name='Função do Responsável')),
                ('rg_responsavel', models.CharField(default='', max_length=20, verbose_name='RG do Responsável')),
                ('cpf_responsavel', models.CharField(default='', max_length=14, verbose_name='CPF do Responsável')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
