# Generated by Django 5.1.9 on 2025-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='cpf_gestor',
            field=models.CharField(default='', max_length=14, unique=True, verbose_name='CPF do Gestor'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cpf_responsavel',
            field=models.CharField(default='', max_length=14, unique=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rg_gestor',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='RG do Gestor'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rg_responsavel',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='RG do Responsável'),
        ),
    ]
